# Generated by Django 5.1 on 2024-08-31 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complejodepadel',
            name='tiene_bar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_dueño_pendiente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complejodepadel',
            name='prestan_paletas',
            field=models.CharField(choices=[('no', 'No'), ('prestan', 'Prestan'), ('alquilan', 'Alquilan'), ('alquilan_y_prestan', 'Alquilan y prestan')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='complejodepadel',
            name='prestan_pelotas',
            field=models.CharField(choices=[('no', 'No'), ('prestan', 'Prestan'), ('alquilan', 'Alquilan'), ('alquilan_y_prestan', 'Alquilan y prestan')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='roles',
            name='nombre',
            field=models.CharField(choices=[('JUGADOR', 'Jugador'), ('DUEÑO', 'Dueño')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('no_validado', 'No validado'), ('pendiente_aprobacion', 'Pendiente aprobación')], default='activo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default='JUGADOR', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.roles'),
        ),
        migrations.CreateModel(
            name='UsersRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.roles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
