# Generated by Django 5.1 on 2024-08-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jugador_jugadorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadorprofile',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
