# Generated by Django 5.1 on 2024-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_complejodepadel_tiene_bar_usuario_es_dueño_pendiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='nombre',
            field=models.CharField(choices=[('JUGADOR', 'Jugador'), ('PROPIETARIO', 'Propietario')], max_length=20),
        ),
    ]
