# Generated by Django 5.1 on 2024-08-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_jugadorprofile_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugadorprofile',
            old_name='usuario',
            new_name='user',
        ),
    ]
