# Generated by Django 5.1 on 2024-08-28 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_complejo_complejoprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplejoDePadel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_complejo', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('habilitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('JUGADOR', 'Jugador'), ('COMPLEJO', 'Complejo')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='complejoprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Complejo',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.RemoveField(
            model_name='jugadorprofile',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='complejodepadel',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.roles'),
        ),
        migrations.DeleteModel(
            name='ComplejoProfile',
        ),
    ]
