# Generated by Django 5.1 on 2024-08-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_complejodepadel_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('no_confirmado', 'No confirmado'), ('pendiente_aprobacion', 'Pendiente aprobacion')], default='activo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='nombre',
            field=models.CharField(choices=[('JUGADOR', 'Jugador'), ('COMPLEJO', 'Complejo'), ('EN_REVISION', 'En_revision')], max_length=20),
        ),
    ]
