# Generated by Django 5.1 on 2024-08-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usuario_estado_alter_roles_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='nombre',
            field=models.CharField(choices=[('JUGADOR', 'Jugador'), ('COMPLEJO', 'Complejo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('no_validad', 'No validado'), ('pendiente_aprobacion', 'Pendiente aprobacion')], default='activo', max_length=20, null=True),
        ),
    ]
