# Generated by Django 5.1 on 2024-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_roles_nombre_alter_usuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complejodepadel',
            name='prestan_paletas',
            field=models.CharField(choices=[('no', 'No'), ('prestan', 'Prestasn'), ('alquilan', 'Alquilan'), ('alquilan_y_prestan', 'Alquilan_y_prestan')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='complejodepadel',
            name='prestan_pelotas',
            field=models.CharField(choices=[('no', 'No'), ('prestan', 'Prestasn'), ('alquilan', 'Alquilan'), ('alquilan_y_prestan', 'Alquilan_y_prestan')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='complejodepadel',
            name='tiene_duchas',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='complejodepadel',
            name='tipo_instalacion',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('ambas', 'Ambas')], max_length=10, null=True),
        ),
    ]
