# Generated by Django 5.1 on 2024-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_complejodepadel_prestan_paletas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complejodepadel',
            name='foto_complejo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
