# Generated by Django 5.1 on 2024-09-22 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_roles_nombre_alter_usuario_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplejosFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='complejodepadel',
            name='prestan_paletas',
            field=models.CharField(choices=[('no', 'No'), ('prestan', 'Prestan'), ('alquilan', 'Alquilan'), ('alquilan_y_prestan', 'Alquilan y prestan')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='complejodepadel',
            name='prestan_pelotas',
            field=models.CharField(choices=[('no', 'No'), ('prestan', 'Prestan'), ('alquilan', 'Alquilan'), ('alquilan_y_prestan', 'Alquilan y prestan')], default='no', max_length=20),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('duracion', models.DurationField()),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.complejodepadel')),
            ],
        ),
    ]
