# Generated by Django 5.1 on 2024-09-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_complejosfotos_turnousuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorariosComplejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion', models.TimeField()),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.complejodepadel')),
            ],
        ),
    ]
