# Generated by Django 5.1 on 2024-10-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_prestan_paletas_complejodepadel_presta_paletas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complejodepadel',
            old_name='presta_paletas',
            new_name='presta_paleta',
        ),
    ]
