# Generated by Django 5.1 on 2024-10-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_presta_paletas_complejodepadel_presta_paleta'),
        ('accounts', '0019_turnousuario_turno_turnousuario_usuario_and_more'),
    ]

    operations = [
    ]
