# Generated by Django 5.1 on 2024-10-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20241004_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnousuario',
            name='estado',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], max_length=20, null=True),
        ),
    ]
