# Generated by Django 5.1 on 2024-10-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_complejodepadel_tipo_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(blank=True, choices=[('reservado', 'Reservado'), ('cancelado', 'Cancelado'), ('pendiente', 'Pendiente'), ('disponible', 'Disponible'), ('finalizado', 'Finalizado'), ('buscando_gente', 'Buscando jugadores')], default='disponible', max_length=20, null=True),
        ),
    ]
