# Generated by Django 5.1 on 2024-10-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_turno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(choices=[('no_tiene', 'No tiene'), ('profesional', 'Profesional'), ('1', 'Primera'), ('2', 'Segunda'), ('3', 'Tercera'), ('4', 'Cuarta'), ('5', 'Quinta'), ('6', 'Sexta'), ('7', 'Septima'), ('8', 'Octava')], default='8', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('no_validado', 'No validado'), ('pendiente_aprobacion', 'Pendiente aprobacion'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], default='pendiente_aprobacion', max_length=20, null=True),
        ),
    ]
