# Generated by Django 5.1 on 2024-11-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_usuario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(choices=[('no', 'No especificado'), ('profesional', 'Profesional'), ('1', 'Primera'), ('2', 'Segunda'), ('3', 'Tercera'), ('4', 'Cuarta'), ('5', 'Quinta'), ('6', 'Sexta'), ('7', 'Septima'), ('8', 'Octava'), ('principiante', 'Principiante')], default='8', max_length=30, null=True),
        ),
    ]
